### ISSUE TITLE
i'm use fetchPage, there some errors.

### ISSUE THREAD

**Issue by arden** [anyong/bookshelf-page#4]
```
ActivityQuiz
    .forge()
    .orderBy('id', 'ASC')
    .fetchPage({
        pageSize: 15,
        page: 3
    })
    .then(function (results) {
        console.log(results);
    })
    .catch(function(error){
        console.log(error);
    });
```

there some errors:

TypeError: Cannot read property 'apply' of undefined
      at QueryBuilder.<anonymous> (/Users/arden/data/repository/trunk/tj/server/tujiaoapi/node_modules/bookshelf-page/lib/index.js:229:33)
      at Object.query (/Users/arden/data/repository/trunk/tj/server/tujiaoapi/node_modules/bookshelf/lib/helpers.js:54:14)
      at query (/Users/arden/data/repository/trunk/tj/server/tujiaoapi/node_modules/bookshelf/lib/model.js:1196:30)
      at count (/Users/arden/data/repository/trunk/tj/server/tujiaoapi/node_modules/bookshelf-page/lib/index.js:220:28)
      at fetchPage (/Users/arden/data/repository/trunk/tj/server/tujiaoapi/node_modules/bookshelf-page/lib/index.js:249:52)
      at /Users/arden/data/repository/trunk/tj/server/tujiaoapi/dist/controllers/ActivityController.js:60:51
      at next (native)
      at step (/Users/arden/data/repository/trunk/tj/server/tujiaoapi/dist/controllers/ActivityController.js:93:191)
      at /Users/arden/data/repository/trunk/tj/server/tujiaoapi/dist/controllers/ActivityController.js:93:451
      at /Users/arden/data/repository/trunk/tj/server/tujiaoapi/dist/controllers/ActivityController.js:93:99
      at getQuizs (/Users/arden/data/repository/trunk/tj/server/tujiaoapi/dist/controllers/ActivityController.js:89:20)
      at dispatch (/Users/arden/data/repository/trunk/tj/server/tujiaoapi/node_modules/koa-compose/index.js:41:32)
      at next (/Users/arden/data/repository/trunk/tj/server/tujiaoapi/node_modules/koa-compose/index.js:42:18)
      at /Users/arden/data/repository/trunk/tj/server/tujiaoapi/node_modules/koa-router/lib/router.js:321:16
      at dispatch (/Users/arden/data/repository/trunk/tj/server/tujiaoapi/node_modules/koa-compose/index.js:41:32)
      at /Users/arden/data/repository/trunk/tj/server/tujiaoapi/node_modules/koa-compose/index.js:34:12
      at dispatch (/Users/arden/data/repository/trunk/tj/server/tujiaoapi/node_modules/koa-router/lib/router.js:326:31)
      at dispatch (/Users/arden/data/repository/trunk/tj/server/tujiaoapi/node_modules/koa-compose/index.js:41:32)
      at next (/Users/arden/data/repository/trunk/tj/server/tujiaoapi/node_modules/koa-compose/index.js:42:18)
      at /Users/arden/data/repository/trunk/tj/server/tujiaoapi/dist/middlewares/KoaLogger.js:57:19
      at next (native)
      at step (/Users/arden/data/repository/trunk/tj/server/tujiaoapi/dist/middlewares/KoaLogger.js:11:191)
      at /Users/arden/data/repository/trunk/tj/server/tujiaoapi/dist/middlewares/KoaLogger.js:11:451
      at /Users/arden/data/repository/trunk/tj/server/tujiaoapi/dist/middlewares/KoaLogger.js:11:99
      at dev (/Users/arden/data/repository/trunk/tj/server/tujiaoapi/dist/middlewares/KoaLogger.js:92:20)
      at dispatch (/Users/arden/data/repository/trunk/tj/server/tujiaoapi/node_modules/koa-compose/index.js:41:32)
      at next (/Users/arden/data/repository/trunk/tj/server/tujiaoapi/node_modules/koa-compose/index.js:42:18)
      at allowedMethods (/Users/arden/data/repository/trunk/tj/server/tujiaoapi/node_modules/koa-router/lib/router.js:361:12)
      at dispatch (/Users/arden/data/repository/trunk/tj/server/tujiaoapi/node_modules/koa-compose/index.js:41:32)
      at next (/Users/arden/data/repository/trunk/tj/server/tujiaoapi/node_modules/koa-compose/index.js:42:18)
      at /Users/arden/data/repository/trunk/tj/server/tujiaoapi/node_modules/koa-bodyparser/index.js:60:14
      at process._tickCallback (node.js:406:9)

**Comment by anyong** [comment]
It looks like `knex#countDistinct` is not defined. What version of knex are you using? `countDistinct` was added later, you might need to update knex.

**Comment by arden** [comment]
i'm sorry, my knex version is too low.
